# Generated by Django 5.0.7 on 2025-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0004_cv_design_cv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default-photo.jpg', upload_to='photos/'),
        ),
    ]
